# Generated by Django 4.1.5 on 2023-01-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0002_usermaster_company_candidate'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='candidate',
            name='birthday',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(max_length=150),
        ),
    ]
