# Generated by Django 4.1.5 on 2023-01-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0003_candidate_highestdu_candidate_job_type_and_more'),
    ]

    