# Generated by Django 4.1.5 on 2023-01-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0004_alter_candidate_min_salary_and_more'),
    ]

   