# Generated by Django 4.1.5 on 2023-01-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0005_remove_candidate_highestdu'),
    ]

    