# Generated by Django 4.1.5 on 2023-01-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0006_candidate_highestdu_alter_candidate_min_salary_and_more'),
    ]

    
