# Generated by Django 4.1.5 on 2023-01-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0007_remove_candidate_min_salary_and_more'),
    ]

