# Generated by Django 4.1.5 on 2023-01-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0008_remove_candidate_country_remove_candidate_shift'),
    ]

   
