# Generated by Django 4.1.5 on 2023-01-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0009_company_firstname_company_lastname'),
    ]

    
