# Generated by Django 4.1.5 on 2023-01-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0010_remove_candidate_highestdu'),
    ]

   
