# Generated by Django 4.1.5 on 2023-01-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0011_remove_candidate_job_type_and_more'),
    ]

   