# Generated by Django 4.1.5 on 2023-01-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0012_candidate_highestdu_candidate_job_type_and_more'),
    ]

    
