# Generated by Django 4.1.5 on 2023-01-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0013_rename_firstname_company_fname_and_more'),
    ]

   