# Generated by Django 4.1.5 on 2023-01-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0014_rename_fname_company_firstname_and_more'),
    ]

    
