# Generated by Django 4.1.5 on 2023-01-23 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0015_candidate_min_salary'),
    ]

  
