# Generated by Django 4.1.5 on 2023-01-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0016_remove_candidate_min_salary'),
    ]

   