# Generated by Django 4.1.5 on 2023-01-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0018_alter_candidate_highestdu'),
    ]

    
