# Generated by Django 4.1.5 on 2023-01-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0019_remove_candidate_highestdu'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='highestdu',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobcategory',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
       
    ]
