# Generated by Django 4.1.5 on 2023-01-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0020_candidate_highestdu_candidate_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='firstname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='lastname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
