# Generated by Django 4.1.5 on 2023-01-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0021_company_firstname_company_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jonname', models.CharField(max_length=250)),
                ('companyname', models.CharField(max_length=250)),
                ('companyaddress', models.CharField(max_length=250)),
                ('jobdescription', models.CharField(max_length=250)),
                ('qualification', models.CharField(max_length=250)),
                ('resposibilities', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('companywebsite', models.CharField(max_length=250)),
                ('companyemail', models.EmailField(max_length=50)),
                ('companycontact', models.CharField(max_length=50)),
                ('salarypackage', models.CharField(max_length=20)),
                ('experience', models.IntegerField()),
                ('logo_pic', models.ImageField(upload_to='ctech/img/company')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctech.company')),
            ],
        ),
    ]
