# Generated by Django 4.1.5 on 2023-01-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctech', '0022_jobdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='company_id',
        ),
    ]
